<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Properties-of-Dot-Product---Lab" data-toc-modified-id="Properties-of-Dot-Product---Lab-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Properties of Dot Product - Lab</a></span><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Objectives" data-toc-modified-id="Objectives-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Objectives</a></span></li><li><span><a href="#Instructions" data-toc-modified-id="Instructions-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Instructions</a></span></li><li><span><a href="#Distributive-Property---matrix-multiplication-IS-distributive" data-toc-modified-id="Distributive-Property---matrix-multiplication-IS-distributive-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Distributive Property - matrix multiplication IS distributive</a></span><ul class="toc-item"><li><span><a href="#Prove-that-$A-\cdot-(B+C)-=-(A-\cdot-B-+-A-\cdot-C)-$" data-toc-modified-id="Prove-that-$A-\cdot-(B+C)-=-(A-\cdot-B-+-A-\cdot-C)-$-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $</a></span></li></ul></li><li><span><a href="#Associative-Property---matrix-multiplication-IS-associative" data-toc-modified-id="Associative-Property---matrix-multiplication-IS-associative-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Associative Property - matrix multiplication IS associative</a></span><ul class="toc-item"><li><span><a href="#Prove-that-$A-\cdot-(B-\cdot-C)-=-(A-\cdot-B)-\cdot-C-$" data-toc-modified-id="Prove-that-$A-\cdot-(B-\cdot-C)-=-(A-\cdot-B)-\cdot-C-$-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $</a></span></li></ul></li><li><span><a href="#Commutative-Property---matrix-multiplication-is-NOT-commutative" data-toc-modified-id="Commutative-Property---matrix-multiplication-is-NOT-commutative-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Commutative Property - matrix multiplication is NOT commutative</a></span><ul class="toc-item"><li><span><a href="#Prove-that-for-matrices,-$A-\cdot-B-\neq-B-\cdot-A-$" data-toc-modified-id="Prove-that-for-matrices,-$A-\cdot-B-\neq-B-\cdot-A-$-1.6.1"><span class="toc-item-num">1.6.1&nbsp;&nbsp;</span>Prove that for matrices, $A \cdot B \neq B \cdot A $</a></span></li></ul></li><li><span><a href="#Commutative-Property----vector-multiplication-IS-commutative" data-toc-modified-id="Commutative-Property----vector-multiplication-IS-commutative-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Commutative Property -  vector multiplication IS commutative</a></span><ul class="toc-item"><li><span><a href="#Prove-that-for-vectors,--$x^T-\cdot-y-=-y^T-\cdot-x$" data-toc-modified-id="Prove-that-for-vectors,--$x^T-\cdot-y-=-y^T-\cdot-x$-1.7.1"><span class="toc-item-num">1.7.1&nbsp;&nbsp;</span>Prove that for vectors,  $x^T \cdot y = y^T \cdot x$</a></span></li></ul></li><li><span><a href="#Simplification-of-the-matrix-product" data-toc-modified-id="Simplification-of-the-matrix-product-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Simplification of the matrix product</a></span><ul class="toc-item"><li><span><a href="#Prove-that-$-(A-\cdot-B)^T-=-B^T-\cdot-A^T-$" data-toc-modified-id="Prove-that-$-(A-\cdot-B)^T-=-B^T-\cdot-A^T-$-1.8.1"><span class="toc-item-num">1.8.1&nbsp;&nbsp;</span>Prove that $ (A \cdot B)^T = B^T \cdot A^T $</a></span></li></ul></li><li><span><a href="#Summary" data-toc-modified-id="Summary-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Summary</a></span></li></ul></li></ul></div>

# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [2]:
# Your code here
import random
def fill(C):
    rows = C.shape[0]
    cols = C.shape[1]

    for x in range(0, rows):
        for y in range(0,cols):
            C[x][y] = random.randint(1,10)
    return C

matrix1 = np.zeros((4,4))
matrix2 = np.zeros((4,4))
matrix3 = np.zeros((4,4))

A = fill(matrix1)
B = fill(matrix2)
C = fill(matrix3)

In [5]:
left = A.dot(B+C)
print(left)

right = A.dot(B) + A.dot(C)
print(right)

[[254. 375. 350. 325.]
 [210. 308. 317. 283.]
 [164. 240. 260. 228.]
 [100. 141. 161. 132.]]
[[254. 375. 350. 325.]
 [210. 308. 317. 283.]
 [164. 240. 260. 228.]
 [100. 141. 161. 132.]]


## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [8]:
# Your code here 
left = A.dot(B.dot(C))
print(left)

right = (A.dot(B)).dot(C)
print(right)

[[2077. 3930. 4281. 3090.]
 [1839. 3521. 3714. 2785.]
 [1496. 2882. 2988. 2286.]
 [ 794. 1526. 1611. 1230.]]
[[2077. 3930. 4281. 3090.]
 [1839. 3521. 3714. 2785.]
 [1496. 2882. 2988. 2286.]
 [ 794. 1526. 1611. 1230.]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [10]:
# Your code here 
left = A.dot(B)
print(left)
right = B.dot(A)
print(right)

[[159. 196. 164. 197.]
 [134. 166. 158. 173.]
 [106. 132. 134. 140.]
 [ 58.  66.  71.  80.]]
[[145.  94.  68.  79.]
 [217. 164. 117. 113.]
 [203. 135.  97. 109.]
 [225. 157. 118. 133.]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [16]:
# Your code here 
import numpy as np

x = np.array([2,3,4,5])
y = np.array([6,7,8,9])

left = (np.transpose(x)).dot(y)
print(left)

right = (np.transpose(y)).dot(x)
print(right)

110
110


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [17]:
# Your code here 
left = np.transpose(A.dot(B))
print(left)

right = np.transpose(B).dot(np.transpose(A))
print(right)

left == right

[[159. 134. 106.  58.]
 [196. 166. 132.  66.]
 [164. 158. 134.  71.]
 [197. 173. 140.  80.]]
[[159. 134. 106.  58.]
 [196. 166. 132.  66.]
 [164. 158. 134.  71.]
 [197. 173. 140.  80.]]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 